default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: entry
  username: root
  password: <%= ENV['ROOT_PASSWORD'] %>

test:
  <<: *default
  database: testdb_jindo
  username: <%= ENV['JINDO_TEST_DATABASE_USERNAME'] %>
  password: <%= ENV['JINDO_TEST_DATABASE_PASSWORD'] %>
  host: <%= ENV['JINDO_TEST_DATABASE_HOST'] %>
  port: 3307

production:
  <<: *default
  database: entry
  username: <%= ENV['JINDO_DATABASE_USERNAME'] %>
  password: <%= ENV['JINDO_DATABASE_PASSWORD'] %>
  host: <%= ENV['JINDO_DATABASE_HOST'] %>
