name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      JINDO_DATABASE_PASSWORD: ${{ secrets.JINDO_DATABASE_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t jindo .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jindo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}