name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      JINDO_TEST_DATABASE_USERNAME: ${{ secrets.JINDO_TEST_DATABASE_USERNAME }}
      JINDO_TEST_DATABASE_PASSWORD: ${{ secrets.JINDO_TEST_DATABASE_PASSWORD }}
      JINDO_TEST_DATABASE_HOST: ${{ secrets.JINDO_TEST_DATABASE_HOST }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      TMAP_APP_KEY: ${{ secrets.TMAP_APP_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6.5

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: run tests
        run: bundle exec rake spec

  CD:
    needs: CI
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      JINDO_DATABASE_PASSWORD: ${{ secrets.JINDO_DATABASE_PASSWORD }}
      TMAP_APP_KEY: ${{ secrets.TMAP_APP_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t jindo .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jindo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
