name: CI

on:
  push:
    branches:
      - master
      - development
      - test-code
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6.5

      - name: install dependencies
        run: bundle install

      - name: run tests
        run: rake spec
