name: CI

on:
  push:
    branches:
      - master
      - development
      - test-code
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      JINDO_TEST_DATABASE_USERNAME: ${{ secrets.JINDO_TEST_DATABASE_USERNAME }}
      JINDO_TEST_DATABASE_PASSWORD: ${{ secrets.JINDO_TEST_DATABASE_PASSWORD }}
      JINDO_TEST_DATABASE_HOST: ${{ secrets.JINDO_TEST_DATABASE_HOST }}

    steps:
      - uses: actions/checkout@v2

      - name: set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6.5

      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: install dependencies
        run: bundle install

      - name: run tests
        run: rake spec
